import{a as w,S as L,i as s}from"./assets/vendor-BBSqv8W6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(t){if(t.ep)return;t.ep=!0;const i=e(t);fetch(t.href,i)}})();const v="33475610-696620aeee3e1938961deeefe",S="https://pixabay.com/api/";async function p(o,r){const e=await w.get(S,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}});return{totalHits:e.data.totalHits,images:e.data.hits}}const P=new L(".gallery a",{captionsData:"alt",captionDelay:250,showCounter:!0}),y=document.querySelector(".loader"),g=document.querySelector(".gallery");function h(){y.style.display="block"}function d(){y.style.display="none"}function R(){g.innerHTML=""}function b(o){const r=o.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}" target="_blank">
            <img src="${e.webformatURL}" alt="${e.tags}" width="300"/>
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>`).join("");g.insertAdjacentHTML("beforeend",r),P.refresh()}function q(){const o=document.querySelector(".gallery-item");if(o){const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}const I=document.querySelector(".form"),E=document.querySelector("input[name='search-text']"),m=document.querySelector(".load-more");let a=1,l="",u=0;function H(){m.style.display="block"}function f(){m.style.display="none"}f();d();I.addEventListener("submit",async o=>{if(o.preventDefault(),l=E.value.trim(),a=1,!l){s.warning({title:"Warning",message:"Please enter a search term.",position:"topRight",timeout:5e3});return}R(),f(),h();let r;try{r=await p(l,a)}catch{s.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",timeout:5e3});return}finally{d()}const{totalHits:e,images:n}=r;if(u=e,n.length===0){s.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3});return}b(n),u<=15?s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3}):H()});m.addEventListener("click",async()=>{const o=a+1;h();let r;try{r=await p(l,o)}catch{s.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",timeout:5e3});return}finally{d()}a=o;const{images:e}=r;b(e),q(),a*15>=u&&(f(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3}))});
//# sourceMappingURL=index.js.map
